library(readxl)
t <- read_excel("/home/pr/plor.xlsx")
hist(t$age, freq = TRUE, main = "Pessoas por idade", xlab = "Idade", ylab = "Quantidade", ylim = range(0,150), xlim = range(t$age), breaks=seq(min(t$age)-0.5, max(t$age)+0.5, by=1), col = "red")
hist(t$failures, freq = T, main = "N º de reprovações", xlab = "Reprovações", ylab = "Quant. Pessoas", ylim = range(0,395), xlim = range(0,4), breaks=seq(min(t$failures)-0.5, max(t$failures)+0.5, by=1), col = "orange")
hist(t$absences, freq = T, main = "Faltas", xlab = "Faltas", ylab = "Quant. de Pessoas", ylim = range(0,150), xlim = range(0,90), breaks=seq(min(t$absences)-0.5, max(t$absences)+0.5, by=1), col = "yellow")
hist(t$G1, freq = T, main = "Notas em matemática - 1º Ano", xlab = "Nota", ylab = "Quant. de Pessoas", ylim = range(0,150), xlim = range(0,20), breaks=seq(min(t$G1)-0.5, max(t$G1)+0.5, by=1), col = "green")
hist(t$G2, freq = T, main = "Notas em matemática - 2º Ano", xlab = "Nota", ylab = "Quant. de Pessoas", ylim = range(0,150), xlim = range(0,20), breaks=seq(min(t$G2)-0.5, max(t$G2)+0.5, by=1), col = "blue")
hist(t$G3, freq = T, main = "Notas em matemática - 3º Ano", xlab = "Nota", ylab = "Quant. de Pessoas", ylim = range(0,150), xlim = range(0,20), breaks=seq(min(t$G3)-0.5, max(t$G3)+0.5, by=1), col = "purple")

boxplot(t$age, horizontal = TRUE, outline = TRUE, names = "Idade", xlim = range(0,2), ylim = range(15,22), col = "red", axes = TRUE)
boxplot(t$failures, horizontal = TRUE, outline = TRUE, names = "Reprovações", xlim = range(0,2), ylim = range(0,5), col = "orange", axes = TRUE)
boxplot(t$absences, horizontal = TRUE, outline = TRUE, names = "Faltas", xlim = range(0,2), ylim = range(0,20), col = "yellow", axes = TRUE)
boxplot(t$G1, horizontal = TRUE, outline = TRUE, names = "G1", xlim = range(0,2), ylim = range(0,20), col = "green", axes = TRUE)
boxplot(t$G2, horizontal = TRUE, outline = TRUE, names = "G2", xlim = range(0,2), ylim = range(0,20), col = "blue", axes = TRUE)
boxplot(t$G3, horizontal = TRUE, outline = TRUE, names = "G3", xlim = range(0,2), ylim = range(0,20), col = "purple", axes = TRUE)
